# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='No-name', max_length=50)),
            ],
            options={
                'ordering': ('name', 'created'),
            },
        ),
    ]
